"""Contains functions that wrap the interpolation types to easily post process data"""

from typing import List, Tuple, Union
from mpi4py import MPI
import numpy as np
from ..io.ppymech.neksuite import pynekread
from ..datatypes.field import FieldRegistry
from ..datatypes.msh import Mesh
from ..datatypes.utils import extrude_2d_sem_mesh
from .pointclouds import generate_1d_arrays
from .probes import Probes
import json


def _as_point(point: Union[List[float], Tuple[float], np.ndarray], name: str) -> np.ndarray:
    point = np.asarray(point, dtype=np.double).reshape(-1)

    if point.size == 2:
        point = np.append(point, 0.0)
    elif point.size != 3:
        raise ValueError(f"{name} must contain either 2 or 3 coordinates")

    return point


def _build_line_points(
    start_point: Union[List[float], Tuple[float], np.ndarray],
    end_point: Union[List[float], Tuple[float], np.ndarray],
    n_points: int,
    mode: str,
    gain: float,
    endpoint: bool,
) -> np.ndarray:
    if n_points < 1:
        raise ValueError("n_points must be at least 1")

    start = _as_point(start_point, "start_point")
    end = _as_point(end_point, "end_point")
    line_vector = end - start
    line_length = np.linalg.norm(line_vector)

    if line_length == 0:
        raise ValueError("start_point and end_point must not be the same point")

    distances = generate_1d_arrays(
        [0.0, line_length], n_points, mode=mode, gain=gain, endpoint=endpoint
    )
    xyz = start.reshape(1, 3) + np.outer(distances / line_length, line_vector)

    return np.column_stack((xyz, distances))


def _field_list_from_input(
    fld: FieldRegistry,
    fields_to_interpolate: Union[list[str], None],
) -> Tuple[list[np.ndarray], list[str], float]:
    if fields_to_interpolate is None:
        fields_to_interpolate = ["all"]

    available_names = list(fld.registry.keys())
    names = available_names if fields_to_interpolate == ["all"] else fields_to_interpolate
    field_list = [fld.registry[name] for name in names]

    return field_list, names, fld.t


def interpolate_along_line(
    comm: MPI.Comm,
    msh: Mesh,
    fld: FieldRegistry,
    start_point: Union[List[float], Tuple[float], np.ndarray],
    end_point: Union[List[float], Tuple[float], np.ndarray],
    n_points: int,
    mode: str = "equal",
    fields_to_interpolate: Union[list[str], None] = None,
    gain: float = 1,
    endpoint: bool = True,
    point_interpolator_type: str = "multiple_point_legendre_numpy",
    max_pts: int = 256,
    find_points_iterative: list = None,
    find_points_comm_pattern: str = "point_to_point",
    elem_percent_expansion: float = 0.01,
    global_tree_type: str = "rank_bbox",
    global_tree_nbins: int = 1024,
    use_autograd: bool = False,
    find_points_tol: float = np.finfo(np.double).eps * 10,
    find_points_max_iter: int = 50,
    local_data_structure: str = "kdtree",
    use_oriented_bbox: bool = False,
    extrusion_lz: Union[int, None] = None,
    extrusion_point_dist: Union[np.ndarray, None] = None,
) -> Tuple[Union[np.ndarray, None], dict[str, np.ndarray]]:
    """
    Interpolate fields along a straight line.

    The line points are generated by applying ``generate_1d_arrays`` to the
    distance interval from ``start_point`` to ``end_point``. Therefore ``mode``,
    ``gain``, and ``endpoint`` have the same meaning as in
    :func:`pysemtools.interpolation.pointclouds.generate_1d_arrays`.

    If the input mesh is 2D, the mesh and fields are first extruded to 3D using
    the same approach as the 2D interpolation example notebook.

    Parameters
    ----------
    comm : MPI.Comm
        MPI communicator.
    msh : Mesh
        Initialized mesh object.
    fld : FieldRegistry
        Initialized field registry.
    start_point, end_point : array-like
        Two- or three-component line endpoints. Two-component points are treated
        as ``z=0``.
    n_points : int
        Number of points along the line.
    mode : str
        Point distribution mode. Uses the same options as ``generate_1d_arrays``.
    fields_to_interpolate : list[str], optional
        Names to interpolate. Use ``["all"]`` or ``None`` to interpolate all
        available fields.

    Returns
    -------
    tuple
        On rank 0, returns ``(line_points, interpolated_data)``. ``line_points``
        has shape ``(n_points, 4)`` with columns ``x, y, z, d``. The dictionary
        maps field names to arrays with one interpolated value per line point.
        Non-root ranks return ``(None, {})``.
    """

    if find_points_iterative is None:
        find_points_iterative = [False, 5000]

    rank = comm.Get_rank()
    if not isinstance(msh, Mesh):
        raise ValueError("msh must be an initialized Mesh object")
    if not isinstance(fld, FieldRegistry):
        raise ValueError("fld must be an initialized FieldRegistry object")

    mesh = msh
    field_data = fld

    if mesh.gdim == 2:
        lz = mesh.lx if extrusion_lz is None else extrusion_lz
        mesh, field_data = extrude_2d_sem_mesh(
            comm, lz=lz, msh=mesh, fld=field_data, point_dist=extrusion_point_dist
        )

    field_list, names, time = _field_list_from_input(field_data, fields_to_interpolate)

    if rank == 0:
        line_points = _build_line_points(
            start_point, end_point, n_points, mode, gain, endpoint
        )
        probes_xyz = line_points[:, :3]
    else:
        line_points = None
        probes_xyz = None

    probes = Probes(
        comm,
        probes=probes_xyz,
        msh=mesh,
        write_coords=False,
        point_interpolator_type=point_interpolator_type,
        max_pts=max_pts,
        find_points_iterative=find_points_iterative,
        find_points_comm_pattern=find_points_comm_pattern,
        elem_percent_expansion=elem_percent_expansion,
        global_tree_type=global_tree_type,
        global_tree_nbins=global_tree_nbins,
        use_autograd=use_autograd,
        find_points_tol=find_points_tol,
        find_points_max_iter=find_points_max_iter,
        local_data_structure=local_data_structure,
        use_oriented_bbox=use_oriented_bbox,
    )
    probes.interpolate_from_field_list(
        time, field_list, comm, write_data=False, field_names=names
    )

    if rank != 0:
        return None, {}

    interpolated_data = {}
    for i, name in enumerate(names):
        interpolated_data[name] = probes.interpolated_fields[:, i + 1]

    return line_points, interpolated_data


def interpolate_fields_from_disk(comm: MPI.Comm,
                                query_points_fname: str,
                                sem_mesh_fname: Union[list, str],
                                field_interpolation_settings: dict,
                                interpolated_fields_output_fname: str = "interpolated_fields.hdf5",
                                dtype: np.dtype = np.single,
                                write_coords: bool = True,
                                point_interpolator_type: str = 'multiple_point_legendre_numpy',
                                max_pts: int = 256,
                                find_points_iterative: list = [False, 5000],
                                find_points_comm_pattern: str = 'point_to_point',
                                elem_percent_expansion: float = 0.01,
                                global_tree_type: str = "rank_bbox",
                                global_tree_nbins: int = 1024,
                                use_autograd: bool = False,
                                find_points_tol: float = np.finfo(np.double).eps * 10,
                                find_points_max_iter: int = 50,
                                local_data_structure: str = "kdtree",
                                use_oriented_bbox: bool = False, 
                                ) -> None:
    """
    Interpolates fields from disk using the probes object.

    This function wraps the probes object to make everything easier to use. 
    It reads the query points and the SEM mesh from disk, and writes the interpolated fields to disk. 
 
    Parameters
    ----------
    comm : MPI.Comm
        The MPI communicator
    query_points_fname : str
        The filename of the query points
    sem_mesh_fname : Union[str, list]
        The filename of the SEM mesh
        if the input is a list, the first element must be the filename and the second element must be the dtype of the SEM mesh in memory
    field_interpolation_settings : dict
        The settings for the field interpolation
        The dictionary must have the following keys:
        "input_type" : str. The type should be either file_sequence or file_index
        "file_sequence" : List[str]. The sequence of files to interpolate if input_type is file_sequence
        "file_index" : str. the name of the index file to use to create the file sequence if input_type is file_index 
        "field_names" : List[str]. The names of the fields to interpolate
    interpolated_fields_output_fname : str, optional
        The filename of the interpolated fields, by default "interpolated_fields.hdf5"
    dtype : np.dtype, optional
        The dtype of the interpolated fields, by default np.single
    write_coords : bool, optional
        Whether to write the coordinates of the query points, by default True
    point_interpolator_type : str, optional
        The type of point interpolator to use, by default 'multiple_point_legendre_numpy'
    max_pts : int, optional
        The maximum number of points to interpolate at once, by default 256
    find_points_iterative : list, optional
        Whether to use iterative point finding, by default [False, 5000]
    find_points_comm_pattern : str, optional
        The communication pattern to use for finding points, by default 'point_to_point'
    elem_percent_expansion : float, optional
        The percent expansion of the elements, by default 0.01
    global_tree_type : str, optional
        The type of global tree to use, by default "rank_bbox"
    global_tree_nbins : int, optional
        The number of bins in the global tree, by default 1024
    use_autograd : bool, optional
        Whether to use autograd, by default False
    find_points_tol : float, optional
        The tolerance for finding points, by default np.finfo(np.double).eps * 10
    find_points_max_iter : int, optional
        The maximum number of iterations for finding points, by default 50 
    """

    # Initialize the probes object given the inputs
    probes = Probes(comm,
        output_fname = interpolated_fields_output_fname,
        probes = query_points_fname,
        msh = sem_mesh_fname,
        write_coords  = write_coords,
        point_interpolator_type = point_interpolator_type,
        max_pts = max_pts,
        find_points_iterative = find_points_iterative,
        find_points_comm_pattern = find_points_comm_pattern ,
        elem_percent_expansion = elem_percent_expansion,
        global_tree_type = global_tree_type,
        global_tree_nbins = global_tree_nbins,
        use_autograd = use_autograd,
        find_points_tol = find_points_tol,
        find_points_max_iter = find_points_max_iter,
        local_data_structure = local_data_structure,
        use_oriented_bbox= use_oriented_bbox,
    )

    # Prepare a list with the inputs
    typ = field_interpolation_settings.get('input_type', None)
    if typ == "file_sequence":
        pass
    elif typ == "file_index":
        
        with open(field_interpolation_settings["file_index"], "r") as infile:
            index_file = json.load(infile)

        field_interpolation_settings['file_sequence'] = []
        for key in index_file.keys():
            try:
                int_key = int(key)
            except ValueError:
                continue
            field_interpolation_settings['file_sequence'].append(index_file[key]['path'])     
    else:
        raise ValueError("The input type must be either file_sequence or file_index")

    # Initialize a field to be used to read
    fld = FieldRegistry(comm)
    
    # Loop throught the files in the sequence
    for fname in field_interpolation_settings['file_sequence']:


        # Read the field in the sequence    
        pynekread(fname, comm, data_dtype=dtype, fld=fld)

        # Prepare a list with the inputs
        if field_interpolation_settings['fields_to_interpolate'] == ["all"]:
            field_list = [fld.registry[key] for key in fld.registry.keys()] 
            field_names = [key for key in fld.registry.keys()]
        else:
            field_list = [fld.registry[key] for key in field_interpolation_settings['fields_to_interpolate']]
            field_names = field_interpolation_settings['fields_to_interpolate']
            
        # Interpolate the fields
        probes.interpolate_from_field_list(fld.t, field_list, comm, write_data=True, field_names=field_names)

        # Clear the fields
        fld.clear()
