name: UnitTesting

# Controls when the action will run.
on:
  workflow_call:

jobs:
  unit_testing:
    name: "Unit testing"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup enviroment
        run: |
          sudo apt-get update
          
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1.2.0
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Upgrade pip and set MPICC
        run: |
          python -m pip install -U pip
          echo "MPICC=$(which mpicc)" >> $GITHUB_ENV
          
      - name: Install packages
        run: | 
          echo "Using MPICC: $MPICC"
          pip install mpi4py --no-cache-dir
          pip install numpy
          pip install scipy
          pip install pymech
          pip install tdqm
          pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install pytest
          pip install pytest-json-report
          pip install pympler
          pip install memory_profiler
          pip install h5py
          pip install rtree
          pip install .
          
      - name: Run unit tests
        run: |
          pytest --json-report -v tests/ | tee unit_tests.txt
      
      - name: Check results
        run: |
          python3 tests/interpret_results.py

      - name: Archive test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: unit_tests.txt
          retention-days: 5
